<?
define('ROOT_INDEX','index.php');
define('LOAD_GET_PAGE','page_id');
define('USER_GET_PAGE','panel');
define('HOME_CMS_PAGE','news');
define('HOME_CMS_USER','reset_character');
define('ACCOUNTSETTINGS_CMS_USER','account_settings');
define('LOGIN_CMS_PAGE','login');
define('USER_CMS_PAGE','user_cp');
define('LOGOUT_CMS_PAGE','logout');
define('REGISTER_CMS_PAGE','register');
define('LOSTPASSWORD_CMS_PAGE','lost_password');
define('ANNOUNCEMENTS_CMS_PAGE','announcements');
define('TERMSOFSERVICE_CMS_PAGE','terms');
?>